# Generated by Django 2.2.4 on 2019-08-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=256)),
                ('level1', models.CharField(max_length=256)),
                ('level2', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('priceSP', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('units', models.CharField(choices=[('шт', 'штука'), ('упак', 'упаковка'), ('рул', 'рулон'), ('пог.м', 'погонный метр'), ('пара', 'пара'), ('меш', 'мешок'), ('M2', 'M2'), ('M3', 'M3'), ('лист', 'лист'), ('кг', 'килограмм')], default='шт', max_length=5)),
                ('pic', models.CharField(max_length=32)),
            ],
        ),
    ]
