# Generated by Django 2.2.4 on 2019-08-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvImport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='level3',
            field=models.CharField(default='none', max_length=256),
        ),
    ]
