# Generated by Django 2.2.4 on 2019-09-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvImport', '0004_auto_20190831_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='нет', max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='joint',
            field=models.CharField(default='нет', max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='property',
            field=models.CharField(default='нет', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='level3',
            field=models.CharField(default='нет', max_length=256),
        ),
    ]
